### ISSUE TITLE
Strange behavior of embedded facebook video

### ISSUE THREAD

**Issue by mathsicist** [dzieje-khorinis/dziejekhorinis.org#1]
**Environment:** Chrome desktop

**Problem description:**
Strange behavior of embedded facebook video. If the video (teaser) is being played, it changes its position while cursor hovering. 
The issue does not occur on all browsers. Check the attached screenshot:
![image](https://user-images.githubusercontent.com/24816670/39831408-a284052c-53c4-11e8-825b-222501f4509d.png)

**Reproduction route:**
1. Navigate to https://dziejekhorinis.org/
2. Scroll down until the video
3. Click the video to play it
4. Hover a cursor on the video and verify whether the issue occurs or not

**Comment by mathsicist** [comment]
The issue occurs on Google Chrome for OS X Version 66.0.3359.181 (Official Build) (64-bit)

**Comment by Azaradel** [comment]
After upgrade to the same version of Chrome as given from you, the problem doesn't occur but I'm using it on linux. Is it possible to be related with specific build of browser not by a version but by an operating system?

**Comment by mathsicist** [comment]
well... I had the same problem on Deeping OS, Chrome browse (I don't remember the version), but on KDE Neon it works fine. I don't know what is the cause.

**Comment by ertrzyiks** [comment]
I have the same problem, Chrome on OSX.

The responsive styles look awkward https://github.com/dzieje-khorinis/dziejekhorinis.org/blob/d1a87e89eec3625ec46e8153da8ea915924e8851/style.css#L98-L100

The facebook video is not responsive by default and this mix of units makes it even worse.

I found some article on this topic, the suggested solution sounds fair enough to me: https://www.ostraining.com/blog/coding/responsive-facebook-videos/
